stages:
  - deploy

deploy_production:
  stage: deploy
  resource_group: arkiv_deploy
  variables:
    DOCKER_IMAGE: arkiv-production
    CONTAINER_NAME: arkiv
    HOST_PORT: "3004"
    DATABASE_NAME: arkiv
    STORAGE_DIR: /srv/arkiv/storage
    NEXT_PUBLIC_APP_URL: https://dashboard.suluinwounderland.com
    NEXT_PUBLIC_BASE_URL: https://dashboard.suluinwounderland.com
    DB_HOST: host.docker.internal
    DB_PORT: "5432"
    DB_USER: postgres
    BIND_ADDRESS: 0.0.0.0
  script:
    - bash .gitlab/deploy-docker.sh
  only:
    - production

deploy_development:
  stage: deploy
  resource_group: arkiv_deploy
  variables:
    DOCKER_IMAGE: arkiv-development
    CONTAINER_NAME: arkiv-development
    HOST_PORT: "3460"
    DATABASE_NAME: db-dev-arkiv
    STORAGE_DIR: /srv/arkiv-dev/storage
    NEXT_PUBLIC_APP_URL: https://dev-sulu.within.ventures
    NEXT_PUBLIC_BASE_URL: https://dev-sulu.within.ventures
  script:
    - bash .gitlab/deploy-docker.sh
  only:
    - development
