stages:
  - deploy

deploy_production:
  stage: deploy
  variables:
    DOCKER_IMAGE: arkiv-production
    CONTAINER_NAME: arkiv
    HOST_PORT: "3004"
    DATABASE_NAME: db-production-arkiv
    NEXT_PUBLIC_APP_URL: https://sulu.within.ventures
    NEXT_PUBLIC_BASE_URL: https://sulu.within.ventures
  script:
    - bash .gitlab/deploy-docker.sh
  only:
    - production

deploy_development:
  stage: deploy
  variables:
    DOCKER_IMAGE: arkiv-development
    CONTAINER_NAME: arkiv-development
    HOST_PORT: "3460"
    DATABASE_NAME: db-dev-arkiv
    NEXT_PUBLIC_APP_URL: https://dev-sulu.within.ventures
    NEXT_PUBLIC_BASE_URL: https://dev-sulu.within.ventures
  script:
    - bash .gitlab/deploy-docker.sh
  only:
    - development
