"use client";

import type { ElementType } from "react";
import type { NavIconName } from "@/lib/iam/types";
import {
  ArchiveBoxIcon,
  ArrowDownOnSquareIcon,
  ArrowRightStartOnRectangleIcon,
  BanknotesIcon,
  BookOpenIcon,
  BriefcaseIcon,
  BuildingOffice2Icon,
  BuildingOfficeIcon,
  BuildingStorefrontIcon,
  CalendarIcon,
  ChartBarIcon,
  ChartPieIcon,
  CheckCircleIcon,
  CircleStackIcon,
  ClipboardDocumentCheckIcon,
  ClipboardDocumentListIcon,
  ClockIcon,
  Cog6ToothIcon,
  CubeIcon,
  CurrencyDollarIcon,
  DocumentMagnifyingGlassIcon,
  DocumentTextIcon,
  HomeIcon,
  IdentificationIcon,
  MapIcon,
  MegaphoneIcon,
  PaperAirplaneIcon,
  PlusIcon,
  PuzzlePieceIcon,
  ShoppingBagIcon,
  ShoppingCartIcon,
  StarIcon,
  SwatchIcon,
  TicketIcon,
  TruckIcon,
  UsersIcon,
  VideoCameraIcon,
} from "@heroicons/react/24/outline";
import {
  ArchiveBoxIcon as ArchiveBoxIconSolid,
  ArrowDownOnSquareIcon as ArrowDownOnSquareIconSolid,
  BanknotesIcon as BanknotesIconSolid,
  BookOpenIcon as BookOpenIconSolid,
  BriefcaseIcon as BriefcaseIconSolid,
  BuildingOffice2Icon as BuildingOffice2IconSolid,
  BuildingOfficeIcon as BuildingOfficeIconSolid,
  BuildingStorefrontIcon as BuildingStorefrontIconSolid,
  CalendarIcon as CalendarIconSolid,
  ChartBarIcon as ChartBarIconSolid,
  ChartPieIcon as ChartPieIconSolid,
  CheckCircleIcon as CheckCircleIconSolid,
  CircleStackIcon as CircleStackIconSolid,
  ClipboardDocumentCheckIcon as ClipboardDocumentCheckIconSolid,
  ClipboardDocumentListIcon as ClipboardIconSolid,
  ClockIcon as ClockIconSolid,
  Cog6ToothIcon as CogIconSolid,
  CubeIcon as CubeIconSolid,
  CurrencyDollarIcon as DollarIconSolid,
  DocumentMagnifyingGlassIcon as DocumentMagnifyingGlassIconSolid,
  DocumentTextIcon as DocumentTextIconSolid,
  HomeIcon as HomeIconSolid,
  IdentificationIcon as IdentificationIconSolid,
  MapIcon as MapIconSolid,
  MegaphoneIcon as MegaphoneIconSolid,
  PaperAirplaneIcon as PaperAirplaneIconSolid,
  PlusIcon as PlusIconSolid,
  PuzzlePieceIcon as PuzzlePieceIconSolid,
  ShoppingBagIcon as ShoppingBagIconSolid,
  ShoppingCartIcon as ShoppingCartIconSolid,
  StarIcon as StarIconSolid,
  SwatchIcon as SwatchIconSolid,
  TicketIcon as TicketIconSolid,
  TruckIcon as TruckIconSolid,
  UsersIcon as UsersIconSolid,
  VideoCameraIcon as VideoCameraIconSolid,
} from "@heroicons/react/24/solid";

type IconSet = {
  outline: ElementType;
  solid: ElementType;
};

const iconMap: Record<NavIconName, IconSet> = {
  home: { outline: HomeIcon, solid: HomeIconSolid },
  users: { outline: UsersIcon, solid: UsersIconSolid },
  clipboard: { outline: ClipboardDocumentListIcon, solid: ClipboardIconSolid },
  star: { outline: StarIcon, solid: StarIconSolid },
  chart: { outline: ChartBarIcon, solid: ChartBarIconSolid },
  settings: { outline: Cog6ToothIcon, solid: CogIconSolid },
  logout: { outline: ArrowRightStartOnRectangleIcon, solid: ArrowRightStartOnRectangleIcon },
  briefcase: { outline: BriefcaseIcon, solid: BriefcaseIconSolid },
  shopping: { outline: ShoppingCartIcon, solid: ShoppingCartIconSolid },
  cube: { outline: CubeIcon, solid: CubeIconSolid },
  pr: { outline: DocumentTextIcon, solid: DocumentTextIconSolid },
  po: { outline: ClipboardDocumentCheckIcon, solid: ClipboardDocumentCheckIconSolid },
  reports: { outline: BookOpenIcon, solid: BookOpenIconSolid },
  sitemap: { outline: BuildingOffice2Icon, solid: BuildingOffice2IconSolid },
  database: { outline: CircleStackIcon, solid: CircleStackIconSolid },
  building: { outline: BuildingOfficeIcon, solid: BuildingOfficeIconSolid },
  identification: { outline: IdentificationIcon, solid: IdentificationIconSolid },
  calendar: { outline: CalendarIcon, solid: CalendarIconSolid },
  "dollar-sign": { outline: CurrencyDollarIcon, solid: DollarIconSolid },
  money: { outline: CurrencyDollarIcon, solid: DollarIconSolid },
  "user-plus": { outline: UsersIcon, solid: UsersIconSolid },
  "file-text": { outline: DocumentTextIcon, solid: DocumentTextIconSolid },
  "chart-bar": { outline: ChartBarIcon, solid: ChartBarIconSolid },
  plus: { outline: PlusIcon, solid: PlusIconSolid },
  "paper-airplane": { outline: PaperAirplaneIcon, solid: PaperAirplaneIconSolid },
  "check-circle": { outline: CheckCircleIcon, solid: CheckCircleIconSolid },
  "chart-pie": { outline: ChartPieIcon, solid: ChartPieIconSolid },
  "arrow-down-on-square": { outline: ArrowDownOnSquareIcon, solid: ArrowDownOnSquareIconSolid },
  truck: { outline: TruckIcon, solid: TruckIconSolid },
  "document-magnifying-glass": {
    outline: DocumentMagnifyingGlassIcon,
    solid: DocumentMagnifyingGlassIconSolid,
  },
  "circle-stack": { outline: CircleStackIcon, solid: CircleStackIconSolid },
  "document-text": { outline: DocumentTextIcon, solid: DocumentTextIconSolid },
  "clipboard-document-check": {
    outline: ClipboardDocumentCheckIcon,
    solid: ClipboardDocumentCheckIconSolid,
  },
  megaphone: { outline: MegaphoneIcon, solid: MegaphoneIconSolid },
  banknotes: { outline: BanknotesIcon, solid: BanknotesIconSolid },
  ticket: { outline: TicketIcon, solid: TicketIconSolid },
  clock: { outline: ClockIcon, solid: ClockIconSolid },
  video: { outline: VideoCameraIcon, solid: VideoCameraIconSolid },
  map: { outline: MapIcon, solid: MapIconSolid },
  palette: { outline: SwatchIcon, solid: SwatchIconSolid },
  plug: { outline: PuzzlePieceIcon, solid: PuzzlePieceIconSolid },
  "shopping-bag": { outline: ShoppingBagIcon, solid: ShoppingBagIconSolid },
  store: { outline: BuildingStorefrontIcon, solid: BuildingStorefrontIconSolid },
  package: { outline: ArchiveBoxIcon, solid: ArchiveBoxIconSolid },
  "bar-chart-3": { outline: ChartBarIcon, solid: ChartBarIconSolid },
};

export function AppSidebarNavIcon({
  name,
  className = "h-5 w-5 shrink-0",
  isActive,
}: {
  name: NavIconName;
  className?: string;
  isActive: boolean;
}) {
  const entry = iconMap[name] ?? iconMap.clipboard;
  const Icon = isActive ? entry.solid : entry.outline;
  return <Icon className={className} />;
}
