/**
 * Prefix menu IAM untuk gate API/halaman.
 * Role baru yang di-grant menu di bawah prefix ini lolos tanpa ubah kode.
 */
export const IAM = {
  dashboard: ["dashboard"],
  ess: ["ess"],
  items: ["items"],
  itemsPurchasing: ["items.product.purchasing", "items.raw-material.purchasing"],
  itemsInventory: ["items.product.inventory", "items.raw-material.inventory"],
  itemsApproval: ["items.product.approval", "items.raw-material.approval"],
  itemsReports: ["items.reports"],
  pos: ["pos"],
  posOperations: ["pos.operations", "pos.cashier.central"],
  posCatalog: ["pos.catalog"],
  posKitchen: ["pos.kitchen"],
  posLoyalty: ["pos.loyalty"],
  posReports: ["pos.reports"],
  posSupervisors: ["pos.settings.supervisors"],
  hris: ["hris"],
  hrisKepegawaian: ["hris.kepegawaian"],
  hrisWorkforce: ["hris.workforce"],
  hrisCompensation: ["hris.compensation"],
  hrisPerformance: ["hris.performance"],
  hrisRecruitment: ["hris.recruitment"],
  accounting: ["accounting"],
  crm: ["crm"],
  crmSettings: ["crm.settings"],
  crmMembers: ["crm.members"],
  crmInbox: ["crm.members.inbox"],
  crmReviews: ["crm.members.reviews"],
  crmLoyalty: ["crm.loyalty"],
  crmReports: ["crm.reports"],
  crmPromo: ["crm.promo", "promo"],
  settings: ["settings"],
  settingsUsers: ["settings.users"],
  settingsRoles: ["settings.roles"],
  settingsMenus: ["settings.menus"],
  settingsBusiness: ["settings.business"],
  settingsIntegrations: ["settings.integrations"],
  settingsAppearance: ["settings.appearance"],
  settingsPaymentGateways: ["settings.payment-gateways"],
  settingsWaGateway: ["settings.wa_gateway"],
  shop: ["shop"],
  ticketing: ["ticketing"],
  ticketingAdmin: [
    "ticketing.settings",
    "ticketing.tickets",
    "ticketing.channel-manager",
    "ticketing.mapping",
  ],
  ticketingOperator: [
    "ticketing.loket",
    "ticketing.gate",
    "ticketing.booking",
    "ticketing.gate_pass",
    "ticketing.passes",
  ],
  ticketingReports: ["ticketing.reports"],
  salesFunnel: ["sales-funnel"],
  promo: ["promo", "crm.promo"],
} as const;

export type IamPrefixGroup = (typeof IAM)[keyof typeof IAM];
