/** Canonical URL namespaces for Items → Raw Material & Product menus. */

export const RM_BASE = "/dashboard/raw-material";
export const PRODUCT_BASE = "/dashboard/product";
export const ITEMS_LANDING_PATH = "/dashboard/items";

export const RM_ROUTES = {
  units: `${RM_BASE}/units`,
  categories: `${RM_BASE}/categories`,
  storage: `${RM_BASE}/storage`,
  materials: `${RM_BASE}/materials`,
  materialsInsert: `${RM_BASE}/materials/insert`,
  materialsDetail: (id: string) => `${RM_BASE}/materials/${id}`,
  materialsEdit: (id: string) => `${RM_BASE}/materials/edit/${id}`,
  materialsBom: (id: string) => `${RM_BASE}/materials/bom/${id}`,
  inventoryStock: `${RM_BASE}/inventory/stock`,
  inventoryOpname: `${RM_BASE}/inventory/opname`,
  inventoryOpnameInsert: `${RM_BASE}/inventory/opname/insert`,
  inventoryOpnameContinue: (id: string) => `${RM_BASE}/inventory/opname/insert?id=${id}`,
  inventoryOpnameDetail: (id: string) => `${RM_BASE}/inventory/opname/${id}`,
  inventoryAdjustment: `${RM_BASE}/inventory/adjustment`,
  inventoryTransfer: `${RM_BASE}/inventory/transfers`,
  purchasingSuppliers: `${RM_BASE}/purchasing/suppliers`,
  purchasingSuppliersInsert: `${RM_BASE}/purchasing/suppliers/insert`,
  purchasingSuppliersDetail: (id: string) => `${RM_BASE}/purchasing/suppliers/${id}`,
  purchasingSuppliersEdit: (id: string) => `${RM_BASE}/purchasing/suppliers/edit/${id}`,
  purchasingPriceList: `${RM_BASE}/purchasing/price-list`,
  purchasingPr: `${RM_BASE}/purchasing/pr`,
  purchasingPrInsert: `${RM_BASE}/purchasing/pr/insert`,
  purchasingPrDetail: (id: string) => `${RM_BASE}/purchasing/pr/${id}`,
  purchasingPrEdit: (id: string) => `${RM_BASE}/purchasing/pr/edit/${id}`,
  purchasingPo: `${RM_BASE}/purchasing/po`,
  purchasingPoInsert: `${RM_BASE}/purchasing/po/insert`,
  purchasingPoDetail: (id: string) => `${RM_BASE}/purchasing/po/${id}`,
  purchasingDelivery: `${RM_BASE}/purchasing/delivery`,
  purchasingGrn: `${RM_BASE}/purchasing/grn`,
  purchasingGrnInsert: `${RM_BASE}/purchasing/grn/insert`,
  purchasingGrnDetail: (id: string) => `${RM_BASE}/purchasing/grn/${id}`,
  purchasingGrnQc: (id: string) => `${RM_BASE}/purchasing/grn/${id}/qc`,
  purchasingGrnContinue: (id: string) => `${RM_BASE}/purchasing/grn/continue/${id}`,
  purchasingReturns: `${RM_BASE}/purchasing/returns`,
  purchasingReturnsInsert: `${RM_BASE}/purchasing/returns/insert`,
  purchasingReturnsDetail: (id: string) => `${RM_BASE}/purchasing/returns/${id}`,
  purchasingReturnsEdit: (id: string) => `${RM_BASE}/purchasing/returns/edit/${id}`,
  purchasingInvoice: `${RM_BASE}/purchasing/invoice`,
  purchasingInvoicePoDetail: (id: string) => `${RM_BASE}/purchasing/invoice/po/${id}`,
  approvalPr: `${RM_BASE}/approval/pr`,
  approvalPo: `${RM_BASE}/approval/po`,
  productionRecipes: `${RM_BASE}/production/recipes`,
  productionHub: `${RM_BASE}/production`,
  productionOrder: (id: string) => `${RM_BASE}/production/orders/${id}`,
} as const;

export const PRODUCT_ROUTES = {
  categories: `${PRODUCT_BASE}/categories`,
  units: `${PRODUCT_BASE}/units`,
  products: `${PRODUCT_BASE}/products`,
  productsInsert: `${PRODUCT_BASE}/products/insert`,
  productsDetail: (id: string) => `${PRODUCT_BASE}/products/${id}`,
  productsEdit: (id: string) => `${PRODUCT_BASE}/products/edit/${id}`,
  productsBom: (id: string) => `${PRODUCT_BASE}/products/bom/${id}`,
  inventoryStock: `${PRODUCT_BASE}/inventory/stock`,
  inventoryOpname: `${PRODUCT_BASE}/inventory/opname`,
  inventoryOpnameInsert: `${PRODUCT_BASE}/inventory/opname/insert`,
  inventoryOpnameContinue: (id: string) => `${PRODUCT_BASE}/inventory/opname/insert?id=${id}`,
  inventoryOpnameDetail: (id: string) => `${PRODUCT_BASE}/inventory/opname/${id}`,
  inventoryAdjustment: `${PRODUCT_BASE}/inventory/adjustment`,
  inventoryTransfer: `${PRODUCT_BASE}/inventory/transfer`,
  purchasingVendor: `${PRODUCT_BASE}/purchasing/vendor`,
  purchasingVendorInsert: `${PRODUCT_BASE}/purchasing/vendor/insert`,
  purchasingVendorDetail: (id: string) => `${PRODUCT_BASE}/purchasing/vendor/${id}`,
  purchasingVendorEdit: (id: string) => `${PRODUCT_BASE}/purchasing/vendor/edit/${id}`,
  purchasingPriceList: `${PRODUCT_BASE}/purchasing/price-list`,
  purchasingPriceListInsert: `${PRODUCT_BASE}/purchasing/price-list/insert`,
  purchasingPriceListDetail: (id: string) => `${PRODUCT_BASE}/purchasing/price-list/${id}`,
  purchasingPriceListEdit: (id: string) => `${PRODUCT_BASE}/purchasing/price-list/edit/${id}`,
  purchasingPr: `${PRODUCT_BASE}/purchasing/pr`,
  purchasingPrInsert: `${PRODUCT_BASE}/purchasing/pr/insert`,
  purchasingPrDetail: (id: string) => `${PRODUCT_BASE}/purchasing/pr/${id}`,
  purchasingPrEdit: (id: string) => `${PRODUCT_BASE}/purchasing/pr/edit/${id}`,
  purchasingPo: `${PRODUCT_BASE}/purchasing/po`,
  purchasingPoInsert: `${PRODUCT_BASE}/purchasing/po/insert`,
  purchasingPoDetail: (id: string) => `${PRODUCT_BASE}/purchasing/po/${id}`,
  purchasingDelivery: `${PRODUCT_BASE}/purchasing/delivery`,
  purchasingDeliveryInsert: `${PRODUCT_BASE}/purchasing/delivery/insert`,
  purchasingDeliveryDetail: (id: string) => `${PRODUCT_BASE}/purchasing/delivery/${id}`,
  purchasingReceive: `${PRODUCT_BASE}/purchasing/receive`,
  purchasingReceiveInsert: `${PRODUCT_BASE}/purchasing/receive/insert`,
  purchasingReceiveDetail: (id: string) => `${PRODUCT_BASE}/purchasing/receive/${id}`,
  purchasingReceiveContinue: (id: string) => `${PRODUCT_BASE}/purchasing/receive/continue/${id}`,
  purchasingReceiveQc: (id: string) => `${PRODUCT_BASE}/purchasing/receive/${id}/qc`,
  purchasingReturns: `${PRODUCT_BASE}/purchasing/returns`,
  purchasingReturnsInsert: `${PRODUCT_BASE}/purchasing/returns/insert`,
  purchasingReturnsDetail: (id: string) => `${PRODUCT_BASE}/purchasing/returns/${id}`,
  purchasingReturnsEdit: (id: string) => `${PRODUCT_BASE}/purchasing/returns/edit/${id}`,
  purchasingInvoice: `${PRODUCT_BASE}/purchasing/invoice`,
  purchasingInvoicePoDetail: (id: string) => `${PRODUCT_BASE}/purchasing/invoice/po/${id}`,
  approvalPr: `${PRODUCT_BASE}/approval/pr`,
  approvalPo: `${PRODUCT_BASE}/approval/po`,
  productionRecipes: `${PRODUCT_BASE}/production/recipes`,
  productionHub: `${PRODUCT_BASE}/production`,
  productionOrder: (id: string) => `${PRODUCT_BASE}/production/orders/${id}`,
} as const;

/** @deprecated Use RM_ROUTES.materials */
export const ITEMS_RAW_MATERIALS_PATH = RM_ROUTES.materials;

/** @deprecated Use PRODUCT_ROUTES.products */
export const ITEMS_PRODUCTS_PATH = PRODUCT_ROUTES.products;

/** @deprecated Use PRODUCT_ROUTES.categories */
export const ITEMS_PRODUCT_CATEGORIES_PATH = PRODUCT_ROUTES.categories;
