export const SUPPLIER_IMPORT_SAMPLE_ROWS: Array<Record<string, string>> = [
  {
    kode: "SUP-2026-0001",
    nama_supplier: "PT Sumber Pangan Nusantara",
    pic_name: "Budi Santoso",
    pic_phone: "081234567890",
    pic_email: "budi@sumberpangan.co.id",
    telepon: "0215551234",
    email: "info@sumberpangan.co.id",
    alamat: "Jl. Industri Raya No. 12",
    kota: "Bandung",
    npwp: "01.234.567.8-901.000",
    payment_terms: "TOP30",
    currency: "IDR",
    bank_nama: "BCA",
    bank_rekening: "1234567890",
    bank_atas_nama: "PT Sumber Pangan Nusantara",
    kategori: "BAHAN_BAKU",
    catatan: "Supplier bahan kering utama",
    status: "active",
  },
  {
    kode: "SUP-2026-0002",
    nama_supplier: "CV Segar Makmur",
    pic_name: "Siti Rahayu",
    pic_phone: "081298765432",
    pic_email: "siti@segarmakmur.com",
    telepon: "0227778899",
    email: "order@segarmakmur.com",
    alamat: "Jl. Pasar Sayur No. 5",
    kota: "Bandung",
    npwp: "",
    payment_terms: "TOP14",
    currency: "IDR",
    bank_nama: "Mandiri",
    bank_rekening: "9876543210",
    bank_atas_nama: "CV Segar Makmur",
    kategori: "SAYUR",
    catatan: "Supplier sayur harian",
    status: "active",
  },
];
