-- =============================================================================
-- Pindahkan tabel public -> schema domain + set search_path
-- Idempoten: aman di fresh DB (no-op) maupun DB yang sudah ada di public.
-- =============================================================================

-- 1) Pastikan semua schema domain ada.
CREATE SCHEMA IF NOT EXISTS "iam";
CREATE SCHEMA IF NOT EXISTS "configuration";
CREATE SCHEMA IF NOT EXISTS "hris";
CREATE SCHEMA IF NOT EXISTS "performance";
CREATE SCHEMA IF NOT EXISTS "recruitment";
CREATE SCHEMA IF NOT EXISTS "item";
CREATE SCHEMA IF NOT EXISTS "purchasing";
CREATE SCHEMA IF NOT EXISTS "inventory";
CREATE SCHEMA IF NOT EXISTS "manufacturing";
CREATE SCHEMA IF NOT EXISTS "pos";
CREATE SCHEMA IF NOT EXISTS "crm";

-- 2) Pindahkan tabel yang masih di public ke schema targetnya.
DO $$
BEGIN
  IF to_regclass('public."activity_logs"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."activity_logs" SET SCHEMA "configuration"'; END IF;
  IF to_regclass('public."admin_user_audit_logs"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."admin_user_audit_logs" SET SCHEMA "configuration"'; END IF;
  IF to_regclass('public."user_approval_permissions"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."user_approval_permissions" SET SCHEMA "configuration"'; END IF;
  IF to_regclass('public."users"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."users" SET SCHEMA "configuration"'; END IF;
  IF to_regclass('public."crm_collectible_avatars"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."crm_collectible_avatars" SET SCHEMA "crm"'; END IF;
  IF to_regclass('public."crm_external_events"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."crm_external_events" SET SCHEMA "crm"'; END IF;
  IF to_regclass('public."crm_integration_partners"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."crm_integration_partners" SET SCHEMA "crm"'; END IF;
  IF to_regclass('public."crm_member_avatar_inventory"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."crm_member_avatar_inventory" SET SCHEMA "crm"'; END IF;
  IF to_regclass('public."crm_member_profiles"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."crm_member_profiles" SET SCHEMA "crm"'; END IF;
  IF to_regclass('public."crm_membership_tiers"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."crm_membership_tiers" SET SCHEMA "crm"'; END IF;
  IF to_regclass('public."crm_redemptions"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."crm_redemptions" SET SCHEMA "crm"'; END IF;
  IF to_regclass('public."crm_rewards"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."crm_rewards" SET SCHEMA "crm"'; END IF;
  IF to_regclass('public."crm_xp_ledger"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."crm_xp_ledger" SET SCHEMA "crm"'; END IF;
  IF to_regclass('public."crm_xp_rules"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."crm_xp_rules" SET SCHEMA "crm"'; END IF;
  IF to_regclass('public."attendance"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."attendance" SET SCHEMA "hris"'; END IF;
  IF to_regclass('public."benefits"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."benefits" SET SCHEMA "hris"'; END IF;
  IF to_regclass('public."departments"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."departments" SET SCHEMA "hris"'; END IF;
  IF to_regclass('public."development_plans"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."development_plans" SET SCHEMA "hris"'; END IF;
  IF to_regclass('public."employee_benefits"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."employee_benefits" SET SCHEMA "hris"'; END IF;
  IF to_regclass('public."employee_documents"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."employee_documents" SET SCHEMA "hris"'; END IF;
  IF to_regclass('public."employee_kpis"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."employee_kpis" SET SCHEMA "hris"'; END IF;
  IF to_regclass('public."employee_salary"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."employee_salary" SET SCHEMA "hris"'; END IF;
  IF to_regclass('public."employee_schedules"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."employee_schedules" SET SCHEMA "hris"'; END IF;
  IF to_regclass('public."employees"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."employees" SET SCHEMA "hris"'; END IF;
  IF to_regclass('public."employment_history"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."employment_history" SET SCHEMA "hris"'; END IF;
  IF to_regclass('public."employment_statuses"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."employment_statuses" SET SCHEMA "hris"'; END IF;
  IF to_regclass('public."hris_logbook_entries"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."hris_logbook_entries" SET SCHEMA "hris"'; END IF;
  IF to_regclass('public."hris_logbook_entry_items"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."hris_logbook_entry_items" SET SCHEMA "hris"'; END IF;
  IF to_regclass('public."hris_logbook_template_items"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."hris_logbook_template_items" SET SCHEMA "hris"'; END IF;
  IF to_regclass('public."hris_logbook_templates"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."hris_logbook_templates" SET SCHEMA "hris"'; END IF;
  IF to_regclass('public."leave_balances"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."leave_balances" SET SCHEMA "hris"'; END IF;
  IF to_regclass('public."leaves"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."leaves" SET SCHEMA "hris"'; END IF;
  IF to_regclass('public."loans"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."loans" SET SCHEMA "hris"'; END IF;
  IF to_regclass('public."offboarding_checklists"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."offboarding_checklists" SET SCHEMA "hris"'; END IF;
  IF to_regclass('public."onboarding_checklists"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."onboarding_checklists" SET SCHEMA "hris"'; END IF;
  IF to_regclass('public."payroll_details"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."payroll_details" SET SCHEMA "hris"'; END IF;
  IF to_regclass('public."payroll_runs"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."payroll_runs" SET SCHEMA "hris"'; END IF;
  IF to_regclass('public."payroll_settings"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."payroll_settings" SET SCHEMA "hris"'; END IF;
  IF to_regclass('public."payroll_tax_config"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."payroll_tax_config" SET SCHEMA "hris"'; END IF;
  IF to_regclass('public."positions"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."positions" SET SCHEMA "hris"'; END IF;
  IF to_regclass('public."project_assignments"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."project_assignments" SET SCHEMA "hris"'; END IF;
  IF to_regclass('public."sections"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."sections" SET SCHEMA "hris"'; END IF;
  IF to_regclass('public."staff"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."staff" SET SCHEMA "hris"'; END IF;
  IF to_regclass('public."staff_schedules"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."staff_schedules" SET SCHEMA "hris"'; END IF;
  IF to_regclass('public."staff_sections"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."staff_sections" SET SCHEMA "hris"'; END IF;
  IF to_regclass('public."finished_goods_inventory"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."finished_goods_inventory" SET SCHEMA "inventory"'; END IF;
  IF to_regclass('public."inventory"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."inventory" SET SCHEMA "inventory"'; END IF;
  IF to_regclass('public."inventory_movements"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."inventory_movements" SET SCHEMA "inventory"'; END IF;
  IF to_regclass('public."bahan_baku"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."bahan_baku" SET SCHEMA "item"'; END IF;
  IF to_regclass('public."brands"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."brands" SET SCHEMA "item"'; END IF;
  IF to_regclass('public."products"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."products" SET SCHEMA "item"'; END IF;
  IF to_regclass('public."produk"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."produk" SET SCHEMA "item"'; END IF;
  IF to_regclass('public."raw_material_unit_conversions"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."raw_material_unit_conversions" SET SCHEMA "item"'; END IF;
  IF to_regclass('public."raw_materials"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."raw_materials" SET SCHEMA "item"'; END IF;
  IF to_regclass('public."satuan"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."satuan" SET SCHEMA "item"'; END IF;
  IF to_regclass('public."units"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."units" SET SCHEMA "item"'; END IF;
  IF to_regclass('public."bom"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."bom" SET SCHEMA "manufacturing"'; END IF;
  IF to_regclass('public."bom_items"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."bom_items" SET SCHEMA "manufacturing"'; END IF;
  IF to_regclass('public."production_batches"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."production_batches" SET SCHEMA "manufacturing"'; END IF;
  IF to_regclass('public."production_order_materials"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."production_order_materials" SET SCHEMA "manufacturing"'; END IF;
  IF to_regclass('public."production_orders"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."production_orders" SET SCHEMA "manufacturing"'; END IF;
  IF to_regclass('public."behavioral_assessments"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."behavioral_assessments" SET SCHEMA "performance"'; END IF;
  IF to_regclass('public."behavioral_review_items"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."behavioral_review_items" SET SCHEMA "performance"'; END IF;
  IF to_regclass('public."behavioral_standards"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."behavioral_standards" SET SCHEMA "performance"'; END IF;
  IF to_regclass('public."feedback_assignments"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."feedback_assignments" SET SCHEMA "performance"'; END IF;
  IF to_regclass('public."feedback_categories"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."feedback_categories" SET SCHEMA "performance"'; END IF;
  IF to_regclass('public."feedback_criteria"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."feedback_criteria" SET SCHEMA "performance"'; END IF;
  IF to_regclass('public."feedback_cycles"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."feedback_cycles" SET SCHEMA "performance"'; END IF;
  IF to_regclass('public."feedback_relationship_types"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."feedback_relationship_types" SET SCHEMA "performance"'; END IF;
  IF to_regclass('public."feedback_responses"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."feedback_responses" SET SCHEMA "performance"'; END IF;
  IF to_regclass('public."feedback_summaries"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."feedback_summaries" SET SCHEMA "performance"'; END IF;
  IF to_regclass('public."kpi_template_behavioral"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."kpi_template_behavioral" SET SCHEMA "performance"'; END IF;
  IF to_regclass('public."kpi_template_items"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."kpi_template_items" SET SCHEMA "performance"'; END IF;
  IF to_regclass('public."kpi_templates"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."kpi_templates" SET SCHEMA "performance"'; END IF;
  IF to_regclass('public."performance_categories"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."performance_categories" SET SCHEMA "performance"'; END IF;
  IF to_regclass('public."performance_reviews"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."performance_reviews" SET SCHEMA "performance"'; END IF;
  IF to_regclass('public."score_scales"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."score_scales" SET SCHEMA "performance"'; END IF;
  IF to_regclass('public."pos_cashier_shifts"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."pos_cashier_shifts" SET SCHEMA "pos"'; END IF;
  IF to_regclass('public."pos_categories"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."pos_categories" SET SCHEMA "pos"'; END IF;
  IF to_regclass('public."pos_customer_vouchers"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."pos_customer_vouchers" SET SCHEMA "pos"'; END IF;
  IF to_regclass('public."pos_customers"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."pos_customers" SET SCHEMA "pos"'; END IF;
  IF to_regclass('public."pos_inventory_settings"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."pos_inventory_settings" SET SCHEMA "pos"'; END IF;
  IF to_regclass('public."pos_kds_orders"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."pos_kds_orders" SET SCHEMA "pos"'; END IF;
  IF to_regclass('public."pos_kds_stations"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."pos_kds_stations" SET SCHEMA "pos"'; END IF;
  IF to_regclass('public."pos_modifier_groups"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."pos_modifier_groups" SET SCHEMA "pos"'; END IF;
  IF to_regclass('public."pos_modifiers"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."pos_modifiers" SET SCHEMA "pos"'; END IF;
  IF to_regclass('public."pos_order_items"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."pos_order_items" SET SCHEMA "pos"'; END IF;
  IF to_regclass('public."pos_order_split_items"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."pos_order_split_items" SET SCHEMA "pos"'; END IF;
  IF to_regclass('public."pos_order_splits"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."pos_order_splits" SET SCHEMA "pos"'; END IF;
  IF to_regclass('public."pos_order_status_history"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."pos_order_status_history" SET SCHEMA "pos"'; END IF;
  IF to_regclass('public."pos_orders"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."pos_orders" SET SCHEMA "pos"'; END IF;
  IF to_regclass('public."pos_print_jobs"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."pos_print_jobs" SET SCHEMA "pos"'; END IF;
  IF to_regclass('public."pos_product_modifiers"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."pos_product_modifiers" SET SCHEMA "pos"'; END IF;
  IF to_regclass('public."pos_product_variants"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."pos_product_variants" SET SCHEMA "pos"'; END IF;
  IF to_regclass('public."pos_products"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."pos_products" SET SCHEMA "pos"'; END IF;
  IF to_regclass('public."pos_recipes"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."pos_recipes" SET SCHEMA "pos"'; END IF;
  IF to_regclass('public."pos_reservations"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."pos_reservations" SET SCHEMA "pos"'; END IF;
  IF to_regclass('public."pos_shift_transactions"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."pos_shift_transactions" SET SCHEMA "pos"'; END IF;
  IF to_regclass('public."pos_shifts"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."pos_shifts" SET SCHEMA "pos"'; END IF;
  IF to_regclass('public."pos_split_payments"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."pos_split_payments" SET SCHEMA "pos"'; END IF;
  IF to_regclass('public."pos_tables"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."pos_tables" SET SCHEMA "pos"'; END IF;
  IF to_regclass('public."pos_vouchers"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."pos_vouchers" SET SCHEMA "pos"'; END IF;
  IF to_regclass('public."pos_wallet_transactions"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."pos_wallet_transactions" SET SCHEMA "pos"'; END IF;
  IF to_regclass('public."pos_xp_config"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."pos_xp_config" SET SCHEMA "pos"'; END IF;
  IF to_regclass('public."pos_xp_transactions"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."pos_xp_transactions" SET SCHEMA "pos"'; END IF;
  IF to_regclass('public."cogs_additional_costs"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."cogs_additional_costs" SET SCHEMA "purchasing"'; END IF;
  IF to_regclass('public."deliveries"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."deliveries" SET SCHEMA "purchasing"'; END IF;
  IF to_regclass('public."goods_receipts"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."goods_receipts" SET SCHEMA "purchasing"'; END IF;
  IF to_regclass('public."gr_items"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."gr_items" SET SCHEMA "purchasing"'; END IF;
  IF to_regclass('public."grn"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."grn" SET SCHEMA "purchasing"'; END IF;
  IF to_regclass('public."grn_items"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."grn_items" SET SCHEMA "purchasing"'; END IF;
  IF to_regclass('public."po_details"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."po_details" SET SCHEMA "purchasing"'; END IF;
  IF to_regclass('public."po_items"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."po_items" SET SCHEMA "purchasing"'; END IF;
  IF to_regclass('public."pr_items"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."pr_items" SET SCHEMA "purchasing"'; END IF;
  IF to_regclass('public."purchase_order_items"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."purchase_order_items" SET SCHEMA "purchasing"'; END IF;
  IF to_regclass('public."purchase_order_payment_terms"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."purchase_order_payment_terms" SET SCHEMA "purchasing"'; END IF;
  IF to_regclass('public."purchase_orders"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."purchase_orders" SET SCHEMA "purchasing"'; END IF;
  IF to_regclass('public."purchase_requests"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."purchase_requests" SET SCHEMA "purchasing"'; END IF;
  IF to_regclass('public."purchase_return_items"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."purchase_return_items" SET SCHEMA "purchasing"'; END IF;
  IF to_regclass('public."purchase_returns"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."purchase_returns" SET SCHEMA "purchasing"'; END IF;
  IF to_regclass('public."qc_inspections"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."qc_inspections" SET SCHEMA "purchasing"'; END IF;
  IF to_regclass('public."returns"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."returns" SET SCHEMA "purchasing"'; END IF;
  IF to_regclass('public."supplier_price_list"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."supplier_price_list" SET SCHEMA "purchasing"'; END IF;
  IF to_regclass('public."supplier_price_lists"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."supplier_price_lists" SET SCHEMA "purchasing"'; END IF;
  IF to_regclass('public."suppliers"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."suppliers" SET SCHEMA "purchasing"'; END IF;
  IF to_regclass('public."vendor_documents"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."vendor_documents" SET SCHEMA "purchasing"'; END IF;
  IF to_regclass('public."vendor_payments"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."vendor_payments" SET SCHEMA "purchasing"'; END IF;
  IF to_regclass('public."vendors"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."vendors" SET SCHEMA "purchasing"'; END IF;
  IF to_regclass('public."candidates"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."candidates" SET SCHEMA "recruitment"'; END IF;
  IF to_regclass('public."interviews"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."interviews" SET SCHEMA "recruitment"'; END IF;
  IF to_regclass('public."job_openings"') IS NOT NULL THEN EXECUTE 'ALTER TABLE public."job_openings" SET SCHEMA "recruitment"'; END IF;
END $$;

-- 3) search_path level database untuk sesi mendatang (psql/tooling lain).
DO $$
BEGIN
  EXECUTE format('ALTER DATABASE %I SET search_path TO public, iam, configuration, hris, performance, recruitment, item, purchasing, inventory, manufacturing, pos, crm, auth', current_database());
END $$;
