/**
 * Sample rows aligned with items-units + items-raw-material-categories seeders.
 * Codes match npm run db:seed:items-* defaults for Sulu Bandung scope.
 */
export const RAW_MATERIAL_IMPORT_SAMPLE_ROWS: Array<Record<string, string>> = [
  {
    kode: "BB-KER-002",
    nama: "Tepung Terigu Protein Tinggi",
    kategori: "KERING",
    satuan_besar_kode: "SACK",
    satuan_kecil_kode: "KG",
    konversi_factor: "25",
    stok_minimum: "2",
    stok_maximum: "20",
    shelf_life_days: "365",
    coa: "PRODUCTION",
    harga_beli: "230000",
    opening_stock: "50",
    stall_code: "MAIN",
    deskripsi: "Tepung terigu serbaguna karung 25 kg",
    status: "active",
  },
  {
    kode: "BB-KER-003",
    nama: "Gula Pasir",
    kategori: "KERING",
    satuan_besar_kode: "KG",
    satuan_kecil_kode: "GR",
    konversi_factor: "1000",
    stok_minimum: "5",
    stok_maximum: "50",
    shelf_life_days: "730",
    coa: "PRODUCTION",
    harga_beli: "16000",
    opening_stock: "15000",
    stall_code: "MAIN",
    deskripsi: "Gula pasir putih",
    status: "active",
  },
  {
    kode: "BB-OIL-001",
    nama: "Minyak Goreng",
    kategori: "OIL",
    satuan_besar_kode: "L",
    satuan_kecil_kode: "ML",
    konversi_factor: "1000",
    stok_minimum: "20",
    stok_maximum: "200",
    shelf_life_days: "365",
    coa: "PRODUCTION",
    harga_beli: "20000",
    opening_stock: "40000",
    stall_code: "MAIN",
    deskripsi: "Minyak goreng sawit",
    status: "active",
  },
  {
    kode: "BB-DAG-002",
    nama: "Daging Sapi Giling",
    kategori: "DAGING",
    satuan_besar_kode: "KG",
    satuan_kecil_kode: "GR",
    konversi_factor: "1000",
    stok_minimum: "3",
    stok_maximum: "30",
    shelf_life_days: "3",
    coa: "PRODUCTION",
    harga_beli: "120000",
    opening_stock: "5000",
    stall_code: "STALL-01",
    deskripsi: "Daging sapi giling segar",
    status: "active",
  },
  {
    kode: "BB-DAI-004",
    nama: "Telur Ayam",
    kategori: "DAIRY",
    satuan_besar_kode: "TRAY",
    satuan_kecil_kode: "BUTIR",
    konversi_factor: "30",
    stok_minimum: "5",
    stok_maximum: "40",
    shelf_life_days: "21",
    coa: "PRODUCTION",
    harga_beli: "55000",
    opening_stock: "90",
    stall_code: "STALL-02",
    deskripsi: "Telur ayam negeri per tray 30 butir",
    status: "active",
  },
  {
    kode: "BB-DAI-001",
    nama: "Susu UHT Full Cream",
    kategori: "DAIRY",
    satuan_besar_kode: "DOS",
    satuan_kecil_kode: "L",
    konversi_factor: "12",
    stok_minimum: "5",
    stok_maximum: "40",
    shelf_life_days: "180",
    coa: "PRODUCTION",
    harga_beli: "180000",
    opening_stock: "24",
    stall_code: "MAIN",
    deskripsi: "Susu UHT 1L per dus isi 12",
    status: "active",
  },
  {
    kode: "BB-KEM-001",
    nama: "Box Takeaway",
    kategori: "KEMASAN",
    satuan_besar_kode: "DOS",
    satuan_kecil_kode: "PCS",
    konversi_factor: "100",
    stok_minimum: "5",
    stok_maximum: "40",
    shelf_life_days: "",
    coa: "PRODUCTION",
    harga_beli: "90000",
    opening_stock: "300",
    stall_code: "STALL-03",
    deskripsi: "Box makanan takeaway per dus 100 pcs",
    status: "active",
  },
  {
    kode: "BB-BAK-001",
    nama: "Gas LPG 12kg",
    kategori: "BAKAR",
    satuan_besar_kode: "CAN",
    satuan_kecil_kode: "KG",
    konversi_factor: "12",
    stok_minimum: "2",
    stok_maximum: "12",
    shelf_life_days: "",
    coa: "PRODUCTION",
    harga_beli: "180000",
    opening_stock: "24",
    stall_code: "MAIN",
    deskripsi: "Tabung gas LPG 12 kg",
    status: "active",
  },
  {
    kode: "BB-NON-001",
    nama: "Sabun Cuci Piring",
    kategori: "NONPANG",
    satuan_besar_kode: "L",
    satuan_kecil_kode: "ML",
    konversi_factor: "1000",
    stok_minimum: "5",
    stok_maximum: "30",
    shelf_life_days: "",
    coa: "ASSET",
    harga_beli: "25000",
    opening_stock: "5000",
    stall_code: "MAIN",
    deskripsi: "Detergen cuci piring konsentrat",
    status: "active",
  },
  {
    kode: "BB-SAY-001",
    nama: "Bawang Merah",
    kategori: "SAYUR",
    satuan_besar_kode: "KG",
    satuan_kecil_kode: "GR",
    konversi_factor: "1000",
    stok_minimum: "5",
    stok_maximum: "50",
    shelf_life_days: "30",
    coa: "PRODUCTION",
    harga_beli: "35000",
    opening_stock: "8000",
    stall_code: "STALL-01",
    deskripsi: "Bawang merah segar kualitas A",
    status: "active",
  },
];
